/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sogou_translate_jni_BreakpadInit */

#ifndef _Included_com_sogou_translate_breakpad_BreakPadCore
#define _Included_com_sogou_translate_breakpad_BreakPadCore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sogou_translate_jni_BreakpadInit
 * Method:    initBreakpadNative
 * Signature: (Ljava/lang/String;Lcom/sogou/translate/jni/InfoHelper;)V
 */
JNIEXPORT void JNICALL Java_com_sogou_translate_breakpad_BreakPadCore_initBreakpadNative
  (JNIEnv *, jclass, jstring, jobject);


/*
 * Class:     com_sogou_translate_jni_BreakpadInit
 * Method:    setInterrupteSysNativeCrash
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_sogou_translate_breakpad_BreakPadCore_setInterrupteSysNativeCrash
        (JNIEnv *, jclass, jboolean);


/*
 * Class:     com_sogou_translate_jni_BreakpadInit
 * Method:    go2crash
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sogou_translate_breakpad_BreakPadCore_go2crash
        (JNIEnv *, jclass);


JNIEXPORT void JNICALL Java_com_sogou_translate_breakpad_BreakPadCore_testUnWind(JNIEnv *env, jclass type);

#ifdef __cplusplus
}
#endif

#endif
