/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sogou_translate_jni_NativeUtils */

#ifndef _Included_com_sogou_translate_jni_NativeUtils
#define _Included_com_sogou_translate_jni_NativeUtils
#ifdef __cplusplus
extern "C" {
#endif


#define DB_PHASE "123457"
/*
 * Class:     com_sogou_translate_jni_NativeUtils
 * Method:    sayHello
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_sogou_translate_jni_NativeUtils_sayHello
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_sogou_translate_jni_NativeUtils
 * Method:    go2Crash
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_sogou_translate_jni_NativeUtils_go2Crash
  (JNIEnv *, jclass);

/*
 * Class:     com_sogou_translate_jni_NativeUtils
 * Method:    getDbPhase
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sogou_translate_jni_NativeUtils_getDbPhase
  (JNIEnv *, jclass);




#ifdef __cplusplus
}
#endif
#endif
